# Generated by Django 2.2.3 on 2019-10-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metas',
            fields=[
                ('nombremeta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('recompensa', models.CharField(max_length=50)),
                ('fechameta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('correo', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('correo', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=40)),
            ],
        ),
    ]
