# Generated by Django 2.2.3 on 2019-11-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sesion',
        ),
    ]
