# Generated by Django 2.2.3 on 2019-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_delete_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='fechameta',
            field=models.DateTimeField(),
        ),
    ]
